<script setup>
	import { Marquee } from "@selemondev/vue3-marquee";
	import "@selemondev/vue3-marquee/dist/style.css";
</script>
<template>
	<Marquee :fade="true" innerClassName="motion-reduce:animate-none motion-reduce:first:hidden gap-[78px]" class="w-full absolute left-1/2 transform -translate-x-1/2 bottom-[18%] max-w-[70%] [--duration:150s] motion-reduce:overflow-auto">
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
		<img src="/marquee/1.png" alt="marquee_1" />
		<img src="/marquee/2.png" alt="marquee_2" />
		<img src="/marquee/3.png" alt="marquee_3" />
		<img src="/marquee/4.png" alt="marquee_4" />
		<img src="/marquee/5.png" alt="marquee_5" />
		<img src="/marquee/6.png" alt="marquee_6" />
		<img src="/marquee/7.png" alt="marquee_7" />
	</Marquee>
</template>
